import { describe, it, expect, vi, beforeEach } from 'vitest';
import { JiraService } from '../jira.js';

describe('JiraService', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  describe('fetchJira', () => {
    it('sends correct headers and credentials', async () => {
      const mockFetch = vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({ ok: true }),
      }));

      await JiraService.fetchJira('test.atlassian.net', '/rest/api/3/myself');

      expect(fetch).toHaveBeenCalledWith(
        'https://test.atlassian.net/rest/api/3/myself',
        expect.objectContaining({
          method: 'GET',
          credentials: 'include',
          headers: expect.objectContaining({
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'X-Atlassian-Token': 'no-check',
          }),
        })
      );
    });

    it('includes body for POST requests', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({}),
      }));

      const body = { jql: 'assignee = currentUser()', fields: ['summary'] };
      await JiraService.fetchJira('test.atlassian.net', '/rest/api/3/search/jql', 'POST', body);

      expect(fetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify(body),
        })
      );
    });

    it('throws on non-OK response', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: false,
        status: 401,
        statusText: 'Unauthorized',
      }));

      await expect(
        JiraService.fetchJira('test.atlassian.net', '/rest/api/3/myself')
      ).rejects.toThrow('Jira API error: 401 Unauthorized');
    });
  });

  describe('createWorklog', () => {
    it('sends correct ADF comment with [Generated by Log Work tool] prefix when addToolPrefix is true', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({ id: '123' }),
      }));

      await JiraService.createWorklog('test.atlassian.net', 'UP-100', {
        timeSpentSeconds: 3600,
        targetDate: '2026-04-08',
        description: 'Implement feature',
        addToolPrefix: true,
      });

      const callBody = JSON.parse(fetch.mock.calls[0][1].body);

      expect(callBody.timeSpentSeconds).toBe(3600);
      expect(callBody.started).toBe('2026-04-08T12:00:00.000+0700');
      expect(callBody.comment.type).toBe('doc');
      expect(callBody.comment.content[0].content[0].text).toBe('[Generated by Log Work tool] Implement feature');
    });

    it('omits the prefix by default (user-created worklogs)', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({ id: '123' }),
      }));

      await JiraService.createWorklog('test.atlassian.net', 'UP-100', {
        timeSpentSeconds: 1800,
        targetDate: '2026-04-08',
        description: 'Manual entry',
      });

      const callBody = JSON.parse(fetch.mock.calls[0][1].body);
      expect(callBody.comment.content[0].content[0].text).toBe('Manual entry');
    });

    it('also reads addToolPrefix flag when GitHub Sync calls it', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({}),
      }));

      await JiraService.createWorklog('test.atlassian.net', 'UP-300', {
        timeSpentSeconds: 900,
        targetDate: '2026-04-09',
        description: 'GitHub sync entry',
        addToolPrefix: true,
      });

      const callBody = JSON.parse(fetch.mock.calls[0][1].body);
      expect(callBody.comment.content[0].content[0].text).toBe('[Generated by Log Work tool] GitHub sync entry');
    });

    it('uses +0700 timezone offset in started field', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({}),
      }));

      await JiraService.createWorklog('test.atlassian.net', 'UP-200', {
        timeSpentSeconds: 1800,
        targetDate: '2026-04-10',
        description: 'test',
      });

      const callBody = JSON.parse(fetch.mock.calls[0][1].body);
      expect(callBody.started).toMatch(/\+0700$/);
    });
  });

  describe('searchJql', () => {
    it('sends JQL as POST with maxResults 50', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({ issues: [] }),
      }));

      await JiraService.searchJql('test.atlassian.net', 'assignee = currentUser()', ['summary']);

      const callBody = JSON.parse(fetch.mock.calls[0][1].body);
      expect(callBody.jql).toBe('assignee = currentUser()');
      expect(callBody.fields).toEqual(['summary']);
      expect(callBody.maxResults).toBe(50);
    });
  });

  describe('getMyProfile', () => {
    it('extracts accountId and cleans displayName', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({
          accountId: 'abc-123',
          displayName: 'John Doe (Company)',
        }),
      }));

      const profile = await JiraService.getMyProfile('test.atlassian.net');
      expect(profile.accountId).toBe('abc-123');
      expect(profile.displayName).toBe('John Doe');
    });

    it('handles displayName without parenthesis', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({
          accountId: 'abc-123',
          displayName: 'Jane Smith',
        }),
      }));

      const profile = await JiraService.getMyProfile('test.atlassian.net');
      expect(profile.displayName).toBe('Jane Smith');
    });
  });

  describe('updateWorklog', () => {
    it('PUTs to the correct endpoint with timeSpentSeconds and ADF comment', async () => {
      const fetchMock = vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({}),
      });
      vi.stubGlobal('fetch', fetchMock);

      await JiraService.updateWorklog('d.atlassian.net', 'UP-1', '12345', {
        timeSpentSeconds: 3600,
        comment: 'Updated description',
      });

      expect(fetchMock).toHaveBeenCalledWith(
        'https://d.atlassian.net/rest/api/3/issue/UP-1/worklog/12345',
        expect.objectContaining({ method: 'PUT' })
      );

      const body = JSON.parse(fetchMock.mock.calls[0][1].body);
      expect(body.timeSpentSeconds).toBe(3600);
      expect(body.comment.content[0].content[0].text).toBe('Updated description');
    });

    it('omits fields that are not provided', async () => {
      const fetchMock = vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({}),
      });
      vi.stubGlobal('fetch', fetchMock);

      await JiraService.updateWorklog('d.atlassian.net', 'UP-1', '12345', {
        timeSpentSeconds: 1800,
      });

      const body = JSON.parse(fetchMock.mock.calls[0][1].body);
      expect(body.timeSpentSeconds).toBe(1800);
      expect(body.comment).toBeUndefined();
    });

    it('does not add the [Generated by Log Work tool] prefix to user-edited comments', async () => {
      const fetchMock = vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({}),
      });
      vi.stubGlobal('fetch', fetchMock);

      await JiraService.updateWorklog('d.atlassian.net', 'UP-1', '12345', {
        comment: 'Plain user comment',
      });

      const body = JSON.parse(fetchMock.mock.calls[0][1].body);
      expect(body.comment.content[0].content[0].text).toBe('Plain user comment');
    });
  });

  describe('fetchMyWorklogs', () => {
    const ME = 'me-account-id';

    function mockSearchResponse(issues) {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({ issues }),
      }));
    }

    it('returns flat list of current user worklogs on the target date, sorted by started', async () => {
      mockSearchResponse([
        {
          key: 'UP-1',
          fields: {
            summary: 'First ticket',
            worklog: {
              worklogs: [
                {
                  id: '20002',
                  author: { accountId: ME },
                  started: '2026-04-15T14:00:00.000+0700',
                  timeSpentSeconds: 1800,
                  comment: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Afternoon work' }] }] },
                },
                {
                  id: '20001',
                  author: { accountId: ME },
                  started: '2026-04-15T09:00:00.000+0700',
                  timeSpentSeconds: 3600,
                  comment: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Morning work' }] }] },
                },
              ],
            },
          },
        },
      ]);

      const rows = await JiraService.fetchMyWorklogs('d.atlassian.net', ME, '2026-04-15');
      expect(rows).toHaveLength(2);
      expect(rows[0].id).toBe('20001');
      expect(rows[0].key).toBe('UP-1');
      expect(rows[0].comment).toBe('Morning work');
      expect(rows[0].timeSpentSeconds).toBe(3600);
      expect(rows[1].id).toBe('20002');
      expect(rows[1].comment).toBe('Afternoon work');
    });

    it('filters out other authors', async () => {
      mockSearchResponse([
        {
          key: 'UP-1',
          fields: {
            summary: 'Shared ticket',
            worklog: {
              worklogs: [
                { author: { accountId: 'someone-else' }, started: '2026-04-15T10:00:00.000+0700', timeSpentSeconds: 600 },
                { author: { accountId: ME }, started: '2026-04-15T11:00:00.000+0700', timeSpentSeconds: 1800 },
              ],
            },
          },
        },
      ]);

      const rows = await JiraService.fetchMyWorklogs('d.atlassian.net', ME, '2026-04-15');
      expect(rows).toHaveLength(1);
      expect(rows[0].timeSpentSeconds).toBe(1800);
    });

    it('filters worklogs to the target local date (handles timezone-aware started)', async () => {
      // First started is on 2026-04-14 in local time, second is 2026-04-15
      mockSearchResponse([
        {
          key: 'UP-1',
          fields: {
            summary: 'Cross-day',
            worklog: {
              worklogs: [
                { author: { accountId: ME }, started: '2026-04-14T23:00:00.000+0700', timeSpentSeconds: 600 },
                { author: { accountId: ME }, started: '2026-04-15T00:30:00.000+0700', timeSpentSeconds: 900 },
              ],
            },
          },
        },
      ]);

      const rows = await JiraService.fetchMyWorklogs('d.atlassian.net', ME, '2026-04-15');
      expect(rows).toHaveLength(1);
      expect(rows[0].timeSpentSeconds).toBe(900);
    });

    it('returns empty list when no issues', async () => {
      mockSearchResponse([]);
      const rows = await JiraService.fetchMyWorklogs('d.atlassian.net', ME, '2026-04-15');
      expect(rows).toEqual([]);
    });

    it('falls back to /worklog endpoint when embedded worklog array hits the 20-item cap', async () => {
      // Embedded array has 20 items, all OLDER than target date (Jira returns oldest-first).
      // The real recent ones live behind the dedicated worklog endpoint.
      const stale = Array.from({ length: 20 }, (_, i) => ({
        id: `old-${i}`,
        author: { accountId: ME },
        started: `2026-04-10T09:00:00.000+0700`,
        timeSpentSeconds: 600,
      }));

      const fresh = [
        {
          id: 'new-1',
          author: { accountId: ME },
          started: '2026-04-15T15:00:00.000+0700',
          timeSpentSeconds: 1800,
          comment: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Recent work' }] }] },
        },
      ];

      const fetchMock = vi.fn((url) => {
        if (url.includes('/rest/api/3/search/jql')) {
          return Promise.resolve({
            ok: true,
            json: () => Promise.resolve({
              issues: [{
                key: 'UP-99',
                fields: { summary: 'Hot ticket', worklog: { worklogs: stale } },
              }],
            }),
          });
        }
        if (url.includes('/rest/api/3/issue/UP-99/worklog')) {
          // Caller is expected to scope by startedAfter/startedBefore
          expect(url).toContain('startedAfter=');
          expect(url).toContain('startedBefore=');
          return Promise.resolve({
            ok: true,
            json: () => Promise.resolve({ worklogs: fresh }),
          });
        }
        return Promise.resolve({ ok: true, json: () => Promise.resolve({}) });
      });
      vi.stubGlobal('fetch', fetchMock);

      const rows = await JiraService.fetchMyWorklogs('d.atlassian.net', ME, '2026-04-15');
      expect(rows).toHaveLength(1);
      expect(rows[0].id).toBe('new-1');
      expect(rows[0].comment).toBe('Recent work');
    });

    it('handles missing comment gracefully', async () => {
      mockSearchResponse([
        {
          key: 'UP-1',
          fields: {
            summary: 'No comment',
            worklog: {
              worklogs: [
                { author: { accountId: ME }, started: '2026-04-15T09:00:00.000+0700', timeSpentSeconds: 1200 },
              ],
            },
          },
        },
      ]);
      const rows = await JiraService.fetchMyWorklogs('d.atlassian.net', ME, '2026-04-15');
      expect(rows[0].comment).toBe('');
    });
  });

  describe('fetchRecentTickets', () => {
    const ME = 'me-account-id';

    it('returns deduplicated tickets sorted by most-recent user worklog', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({
          issues: [
            {
              key: 'UP-1',
              fields: {
                summary: 'Older',
                worklog: { worklogs: [
                  { author: { accountId: ME }, started: '2026-05-01T09:00:00.000+0700' },
                ] },
              },
            },
            {
              key: 'UP-2',
              fields: {
                summary: 'Newest',
                worklog: { worklogs: [
                  { author: { accountId: ME }, started: '2026-05-08T09:00:00.000+0700' },
                  { author: { accountId: 'someone-else' }, started: '2026-05-09T09:00:00.000+0700' },
                ] },
              },
            },
          ],
        }),
      }));

      const tickets = await JiraService.fetchRecentTickets('d.atlassian.net', ME, 7);
      expect(tickets.map((t) => t.key)).toEqual(['UP-2', 'UP-1']);
      expect(tickets[0]).toEqual({ key: 'UP-2', summary: 'Newest' });
    });

    it('sends the JQL with the requested day window', async () => {
      const fetchMock = vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({ issues: [] }),
      });
      vi.stubGlobal('fetch', fetchMock);

      await JiraService.fetchRecentTickets('d.atlassian.net', ME, 14);
      const body = JSON.parse(fetchMock.mock.calls[0][1].body);
      expect(body.jql).toContain('worklogDate >= -14d');
    });
  });
});
